Algo-Phantoms/Algo-ScriptML

Lasso Regression/Lasso_Regression.py, Lasso Regression/README.md, Ridge Regression/README.md
Implemented Lasso Regression, Updated ReadMe for Lasso Regression.
Ref -Issue (#30 )
=> Lasso_Regression - Base

K-Means/README.md
Fixes #58 
I have added the documentation for K-Means and tried to cover the main points.
Please review and let me know if any changes/improvisation are necessary.
=> Issue 58: K-Means algorithm - Documentation

Bayesian Regression/README.md
Here I have tried to give a brief explanation of Bayesian Regression for the beginners and people on intermediate level .I have tried to explain each and every  keypoint /factor on which the model depends on. I didn't take down the mathematical proof as it would be intimidating for beginners. Please go through it and do let me know if any improvisation/changes are necessary.
=> Bayesian Regression - Documentation 

stochastic gradient descent/README.md, stochastic gradient descent/stochastic_gradient_descent_algo.py
algorithm,explanation and documentation added
issue #61
=> Stochastic Gradient Descent - Base and Documentation

Random Forest/randomForest.py, Random Forest/randomForestTest.py
(Issue #42)Base code for Random Forest is Added with test code 
the files are located at  Algo-ScriptML\Random Forest\   name as "randomForest.py " and "randomForestTest.py"
Please merge it and help me to make my first contribution to my GSSoC'21 journey 
If it doesn't stand out at your expectations do let me know
=> Random Forest is added

Gaussian Mixture Model/README.md
I have completed the documentation of Gaussian Mixture Model for issue #142 .
=> Completed the documentation for Gaussian Mixture Model

K Nearest Neighbors/README.md
=> Update README.md KNN documentation 

Linear discriminant analysis/README.md
I have successfully completed the documentation for LDA with proper format and order for issue #154
=> Completed the documentation for LDA

Apriori/README.md
I've added the README.md for Apriori Algorithm giving its appropriate description as well as mentioning its advantages and disadvantages.
This PR is with reference to issue #137. @geekquad please check this out.
=> README for Apriori Algorithm Added

Genetic Algorithm/README.md
I have add readme file for GA. Please review it.
Fix issue #181
=> Add Genetic Algorithm

Naive Bayes/naive_bayes.py
I've added the code for implementing Naïve Bayes algorithm from scratch. This PR is with reference to issue #176. @geekquad please check this out.
=> Naïve Bayes Algorithm Added

FP-Growth/README.md
I've added README for 'FP Growth' algorithm. @yukti845 @geekquad please check this PR with reference to issue #170.
=> FP Growth - Documentation

Multiple Linear Regression/README.md
I've added README for 'Multiple Linear Regression' algorithm. @yukti845 please check.
=> Multiple Linear Regression - Documentation

Elastic Net/README.md
I've added README for 'Elastic Net Regression' algorithm. @geekquad please check it out.
=> Elastic Net Regression - Documentation

Lowess Regression/README.md
I've added README for 'Lowess Regression' algorithm. @geekquad please check it out.
=> Lowess Regression - Documentation

Spectral Clustering/README.md
With reference to issue 'Clustering Documentation' (#121), I've added the documentation for 'Spectral Clustering'.
=> Spectral Clustering - Documentation

Spectral Clustering/spectral_clustering.py
I've added the implementation code for 'Spectral Clustering' algorithm. @geekquad please check it out.
=> Spectral Clustering - Base

Mini Batch K-means Clustering/README.md
With reference to issue 'Clustering Documentation' (#121), I've added the documentation for 'Mini Batch K-means Clustering' too.
=> Mini Batch K-means Clustering - Documentation

XGBoost/README.md
I have added the XGBoost Documentation with reference to issue (#67). @geekquad please check it out.
=> XGBoost - Documentation

BIRCH Clustering/README.md
With reference to issue 'Clustering Documentation' (#121), I've added the documentation for 'BIRCH Clustering' as well.
=> BIRCH Clustering - Documentation

Multiple Linear Regression/multiple_linear_regression_implementation.py
I've added the implementation code for 'Multiple Linear Regression' algorithm. @yukti845 please check it out.
=> Multiple Linear Regression - Base
